#!/bin/bash

TARGET="tester"

CGO_LDFLAGS="-L lib/mac -rpath lib/mac" go test -c -o $TARGET
#install_name_tool -change @loader_path/libbass.dylib @loader_path/lib/mac/libbass.dylib $TARGET

./$TARGET
rm $TARGET